apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: {{ .Values.mysqlService.type }}
  ports:
  - port: {{ .Values.mysqlService.port }}
    targetPort: 3306
  selector:
    app: mysql
