# Dockerfile for Ghost
FROM ghost:latest

# Environment variables
ENV database__client=mysql
ENV database__connection__host=mysql-service
ENV database__connection__user=root
ENV database__connection__password=example
ENV database__connection__database=ghost

EXPOSE 2368
